<div class="container-fluid">
    <div class="row">
        <div class="col">
            <div
                    class="report-run-on-event"
                    id="affiliateAdsContainer"
                    data-action="wpe_affiliate_get_adverts"
                    data-trigger-selector="#wpeAffiliateContainer .nav-tabs .nav-link"
                    data-trigger-event="shown.bs.tab"
                    data-body-selector="#wpe_affiliate_get_adverts .card-body"
                    data-data=""
            >

                <div class="card w-100 " id="wpe_affiliate_get_adverts">
                    <div class="card-header">Affiliate Adverts</div>
                    <div class="card-body">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>