<?php
$settingsConf = \WPEAffiliate\Modules\AffiliateAdverts\Controller\ModuleController::$moduleConfig['settings'];
$optionName = $settingsConf['optionName'];
$settings = get_option($optionName);
$saveSettingsNonceAction = \WPEAffiliate\Modules\AffiliateAdverts\Controller\SettingsController::$saveNonceAction;
$saveSettingsNonce = wp_create_nonce($saveSettingsNonceAction);
?>

<form method="post" novalidate="novalidate" id="settingsForm">
    <div id="apiResponseFeedback" class="alert fade"></div>
    <input type="hidden" id="_wpnonce" name="_wpnonce" value="<?= $saveSettingsNonce ?>"/>
    <div class="container-fluid wpe-div-table table-striped">
        <h2>WPEasy User Details:</h2>
        <div class="row">
            <div class="col-12 col-sm-2">
                Registered Email
            </div>
            <div class="col-12 col-sm-5">
                <div class="input-group">
                    <input
                            id="affiliateEmail"
                            type="email"
                            class="form-control"
                            name="<?= $optionName ?>[email]"
                            placeholder="EMAIL"
                            value="<?= @$settings['email'] ?>"
                    />
                    <div class="input-group-append">
                        <button id="getAffiliateIdBtn" class="btn btn-outline-secondary" type="button"><span
                                    class="wpe-spinner-small d-none"></span>Get My ID
                        </button>
                    </div>
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-2">
                ID
            </div>
            <div class="col-12 col-sm-5">
                <input
                        id="affiliateID"
                        type="text"
                        class="form-control"
                        name="<?= $optionName ?>[id]"
                        placeholder="WPEasy Affiliate ID"
                        value="<?= @$settings['id'] ?>"
                />
            </div>
        </div>

    </div>

    <button type="submit" class="btn btn-primary " id="submitButton">Save Changes <span
                class="wpe-spinner-small d-none"></span></button>

</form>
<script>
    (function ($) {

        let $settingsFrom = $('#settingsForm');
        let $submitButtonSpinner = $('#submitButton .wpe-spinner-small');
        let $apiResponseFeedback = $('#apiResponseFeedback');

        $('#getAffiliateIdBtn').on('click', function (e) {
            e.preventDefault();
            let $this = $(this);
            let $spinner = $this.find('.wpe-spinner-small');
            let $affiliateID = $('#affiliateID');
            let wpe = window.wpeAffiliate;

            //Reset spinners and alerts
            $spinner.removeClass('d-none');
            $apiResponseFeedback.removeClass('alert-success alert-warning alert-danger');
            $apiResponseFeedback.removeClass('show');

            wpe.Api.doCall('/user/getAffiliateByEmail', {'email' : $('#affiliateEmail').val()})
                .then(function (result) {
                    if(result.data && result.data.affiliate.affiliate_id){
                        $affiliateID.val(result.data.affiliate.affiliate_id);
                        $apiResponseFeedback.html('ID found and inserted in to input');
                        $apiResponseFeedback.addClass('alert-success');
                    }else{
                        $affiliateID.val('');
                        $apiResponseFeedback.html('User found but is not an affiliate');
                        $apiResponseFeedback.addClass('alert-warning');
                    }
                })
                .catch(function (err) {
                    console.log('ERR:', err);
                    $apiResponseFeedback.html('ERROR (' + err.status + ') ' + err.statusText);
                    $apiResponseFeedback.addClass('alert-danger');
                    $affiliateID.val('');
                })
                .finally(function () {
                    console.info('FINALLY');
                    $apiResponseFeedback.addClass('show');
                    $spinner.addClass('d-none');
                })
        })


        $settingsFrom.on('submit', function (e) {
            e.preventDefault();
            $submitButtonSpinner.removeClass('d-none');
            $apiResponseFeedback.removeClass('alert-success alert-warning alert-danger');
            $apiResponseFeedback.removeClass('show');

            $.post(
                {
                    url: window.ajaxurl,
                    data: {action: "<?= $saveSettingsNonceAction ?>", nonce: $('#_wpnonce').val(), data: $(this).serialize()}
                }
            )
                .done(function (result) {
                    $apiResponseFeedback.html('Settings Saved');
                    $apiResponseFeedback.addClass('alert-success');
                })
                .fail(function (err) {
                    console.log('ERROR', err);
                    $apiResponseFeedback.html('ERROR (' + err.status + ') ' + err.statusText);
                    $apiResponseFeedback.addClass('alert-danger');

                })
                .always(function () {
                    $submitButtonSpinner.addClass('d-none');
                    $apiResponseFeedback.addClass('show');
                })
        })
    })(jQuery)
</script>
