<?php
$settingsConf = \WPEAffiliate\Modules\AffiliateAdverts\Controller\ModuleController::$moduleConfig['settings'];
$optionName = $settingsConf['optionName'];
$settings = get_option($optionName);
$settingsNonce = wp_create_nonce(\WPEAffiliate\Modules\AffiliateAdverts\Controller\SettingsController::$nonceAction)
?>

<form method="post" novalidate="novalidate" id="settingsForm">
    <div id="apiErrorAlert" class="alert alert-danger fade"></div>
    <input type="hidden" id="_wpnonce" name="_wpnonce" value="<?= $settingsNonce ?>"/>
    <div class="container-fluid wpe-div-table table-striped">
        <h2>WPEasy User Details:</h2>
        <div class="row">
            <div class="col-12 col-sm-2">
                Registered Email
            </div>
            <div class="col-12 col-sm-5">
                <div class="input-group">
                    <input
                            id="affiliateEmail"
                            type="email"
                            class="form-control"
                            name="<?= $optionName ?>[email]"
                            placeholder="EMAIL"
                            value="<?= @$settings['email'] ?>"
                    />
                    <div class="input-group-append">
                        <button id="getAffiliateIdBtn" class="btn btn-outline-secondary" type="button"><span
                                    class="wpe-spinner-small d-none"></span>Get My ID
                        </button>
                    </div>
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-12 col-sm-2">
                ID
            </div>
            <div class="col-12 col-sm-5">
                <input
                        id="affiliateID"
                        type="text"
                        class="form-control"
                        name="<?= $optionName ?>[id]"
                        placeholder="WPEasy Affiliate ID"
                        value="<?= @$settings['id'] ?>"
                />
            </div>
        </div>

    </div>

    <button type="submit" class="btn btn-primary " id="submitButton">Save Changes <span
                class="wpe-spinner-small d-none"></span></button>

</form>
<script>
    (function ($) {

        let $settingsFrom = $('#settingsForm');
        let $submitButtonSpinner = $('#submitButton .wpe-spinner-small');

        $('#getAffiliateIdBtn').on('click', function (e) {
            e.preventDefault();
            let $this = $(this);
            let $spinner = $this.find('.wpe-spinner-small');
            let $affiliateID = $('#affiliateID');
            let $apiErrorAlert = $('#apiErrorAlert');
            let wpe = window.wpeAffiliate;

            $spinner.removeClass('d-none');
            wpe.Api.doCall('/user/getAffiliateByEmail', {'email' : $('#affiliateEmail').val()})
                .then(function (result) {
                    if(result.data && result.data.affiliate.affiliate_id){
                        $affiliateID.val(result.data.affiliate.affiliate_id);
                    }else{
                        $affiliateID.val('');
                    }
                })
                .catch(function (err) {
                    console.log('ERR:', err);
                    $apiErrorAlert.html('ERROR (' + err.status + ') ' + err.statusText);
                    $apiErrorAlert.addClass('show');
                    $affiliateID.val('');
                })
                .finally(function () {
                    $spinner.removeClass('show');
                })


        })


        $settingsFrom.on('submit', function (e) {
            e.preventDefault();
            $submitButtonSpinner.removeClass('d-none');
            $.post(
                {
                    url: window.ajaxurl,
                    data: {action: 'wpe_affiliate_save', nonce: $('#_wpnonce').val(), data: $(this).serialize()}
                }
            )
                .done(function (result) {
                    //location.reload();
                })
                .fail(function (err) {
                    console.log('ERROR', err);

                })
                .always(function () {
                    $submitButtonSpinner.addClass('d-none');
                })
        })
    })(jQuery)
</script>
